apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cinegest-front-vault
  namespace: cinegest-site
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-frontend
    kind: SecretStore
  target:
    name: cinegest-front-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Variables d'environnement pour Next.js
        API_URL: "{{ .API_URL }}"
        ENV_REFERER: "{{ .ENV_REFERER }}"
  dataFrom:
    - extract:
        key: cinegest-site/cinegest-front/app
